jwt:
  wjx-test: wjx44445
  expires-time: 7d
  buffer-time: 1d


# zap logger configuration
zap:
  level: info
  prefix: '[https://github.com/WJX2001/my-gin-admin]'
  format: console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  show-line: true
  log-in-console: false
  retention-day: -1
  access-req-body: true
  access-resp-data: true
  access-req-headers: true
  access-log-max-bytes: 1024
  file-only-modules:
    - http
    - sql

# system configuration
system:
  addr: 8080
  db-type: mysql
  # 禁用自动迁移数据库表结构，生产环境建议设为true，手动迁移
  disable-auto-migrate: false

mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: gin_admin
  username: root
  password: root123
  engine: InnoDB
  log-mode: info
  max-idle-conns: 10
  max-open-conns: 100
  singular: false

