
jwt:
  wjx-test: wjx44445

system:
  db-type: mysql
  # 禁用自动迁移数据库表结构，生产环境建议设为true，手动迁移
  disable-auto-migrate: false

mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: gin_admin
  username: root
  password: root123
  engine: InnoDB
  log-mode: info
  max-idle-conns: 10
  max-open-conns: 100
  singular: false
